version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: etma-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: etma
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - etma-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: etma-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
              PORT: 5002
      MONGODB_URI: mongodb://root:root123@mongodb:27017/etma?retryWrites=true&w=majority
      JWT_SECRET: sua_chave_secreta_jwt_aqui_mude_em_producao
      FRONTEND_URL: http://localhost:3002
    ports:
      - "5002:5002"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - etma-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: etma-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5002/api
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - etma-network

  # Nginx (opcional - para produção)
  nginx:
    image: nginx:alpine
    container_name: etma-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - etma-network

volumes:
  mongodb_data:

networks:
  etma-network:
    driver: bridge
